/* Generated By:JavaCC: Do not edit this line. ATKScriptParserVisitor.java Version 5.0 */
package com.orange.atk.interpreter.parser;

import com.orange.atk.interpreter.ast.ASTBOOLEAN;
import com.orange.atk.interpreter.ast.ASTCOMMENT;
import com.orange.atk.interpreter.ast.ASTFLOAT;
import com.orange.atk.interpreter.ast.ASTFUNCTION;
import com.orange.atk.interpreter.ast.ASTINCLUDE;
import com.orange.atk.interpreter.ast.ASTLOOP;
import com.orange.atk.interpreter.ast.ASTNUMBER;
import com.orange.atk.interpreter.ast.ASTSETVAR;
import com.orange.atk.interpreter.ast.ASTSTRING;
import com.orange.atk.interpreter.ast.ASTStart;
import com.orange.atk.interpreter.ast.ASTTABLE;
import com.orange.atk.interpreter.ast.ASTVARIABLE;
import com.orange.atk.interpreter.ast.SimpleNode;
import com.orange.atk.interpreter.parser.*;

public interface ATKScriptParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTCOMMENT node, Object data);
  public Object visit(ASTFUNCTION node, Object data);
  public Object visit(ASTINCLUDE node, Object data);
  public Object visit(ASTSETVAR node, Object data);
  public Object visit(ASTLOOP node, Object data);
  public Object visit(ASTTABLE node, Object data);
  public Object visit(ASTSTRING node, Object data);
  public Object visit(ASTNUMBER node, Object data);
  public Object visit(ASTBOOLEAN node, Object data);
  public Object visit(ASTFLOAT node, Object data);
  public Object visit(ASTVARIABLE node, Object data);
}
/* JavaCC - OriginalChecksum=a3d79c10f79c9288b3bbaf8d097e457c (do not edit this line) */
