/* Generated By:JJTree: Do not edit this line. ASTBOOLEAN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.orange.atk.interpreter.ast;

import com.orange.atk.interpreter.parser.*;

public
class ASTBOOLEAN extends SimpleNode {
  public ASTBOOLEAN(int id) {
    super(id);
  }

  public ASTBOOLEAN(ATKScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ATKScriptParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=15db3437e020ff693a5fefea1550e4ed (do not edit this line) */
