/* Generated By:JJTree: Do not edit this line. ASTTABLE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.orange.atk.interpreter.ast;

import com.orange.atk.interpreter.parser.*;
import com.orange.atk.interpreter.parser.ATKScriptParserVisitor;

public
class ASTTABLE extends SimpleNode {
  public ASTTABLE(int id) {
    super(id);
  }

  public ASTTABLE(ATKScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ATKScriptParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b6ef55bdc6574d6d59cb87ca0a93eee2 (do not edit this line) */
