/* Generated By:JavaCC: Do not edit this line. ATKScriptParserTreeConstants.java Version 5.0 */
package com.orange.atk.interpreter.parser;

import com.orange.atk.interpreter.parser.*;

public interface ATKScriptParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTCOMMENT = 2;
  public int JJTFUNCTION = 3;
  public int JJTINCLUDE = 4;
  public int JJTSETVAR = 5;
  public int JJTLOOP = 6;
  public int JJTTABLE = 7;
  public int JJTSTRING = 8;
  public int JJTNUMBER = 9;
  public int JJTBOOLEAN = 10;
  public int JJTFLOAT = 11;
  public int JJTVARIABLE = 12;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "COMMENT",
    "FUNCTION",
    "INCLUDE",
    "SETVAR",
    "LOOP",
    "TABLE",
    "STRING",
    "NUMBER",
    "BOOLEAN",
    "FLOAT",
    "VARIABLE",
  };
}
/* JavaCC - OriginalChecksum=d5bf8aaf654c85ef11262e35474519de (do not edit this line) */
