/* Generated By:JJTree&JavaCC: Do not edit this line. ATKScriptParserConstants.java */
package com.orange.atk.interpreter.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ATKScriptParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LOOP = 3;
  /** RegularExpression Id. */
  int ENDL = 4;
  /** RegularExpression Id. */
  int INCLUDE = 5;
  /** RegularExpression Id. */
  int SETVAR = 6;
  /** RegularExpression Id. */
  int NUMBER = 7;
  /** RegularExpression Id. */
  int DIGIT = 8;
  /** RegularExpression Id. */
  int EOL = 9;
  /** RegularExpression Id. */
  int VARNAME = 10;
  /** RegularExpression Id. */
  int STRING = 11;
  /** RegularExpression Id. */
  int CHAR = 12;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"loop\"",
    "\"endloop\"",
    "\"Include\"",
    "\"SetVar\"",
    "<NUMBER>",
    "<DIGIT>",
    "<EOL>",
    "<VARNAME>",
    "<STRING>",
    "<CHAR>",
    "<SINGLE_LINE_COMMENT>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
  };

}
