/* Generated By:JJTree: Do not edit this line. ASTCOMMENT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.orange.atk.interpreter.ast;

import com.orange.atk.interpreter.parser.*;
import com.orange.atk.interpreter.parser.ATKScriptParserVisitor;

public
class ASTCOMMENT extends SimpleNode {
  public ASTCOMMENT(int id) {
    super(id);
  }

  public ASTCOMMENT(ATKScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ATKScriptParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cb1327c8a1a0e653990421bf5ac94eb7 (do not edit this line) */
