/* Generated By:JJTree: Do not edit this line. ASTSTRING.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.orange.atk.interpreter.ast;

import com.orange.atk.interpreter.parser.*;
import com.orange.atk.interpreter.parser.ATKScriptParserVisitor;

public
class ASTSTRING extends SimpleNode {
  public ASTSTRING(int id) {
    super(id);
  }

  public ASTSTRING(ATKScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ATKScriptParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9354d5d2fdb748c458b65cf5071393ae (do not edit this line) */
